imagePullPolicy: IfNotPresent
evisionHistoryLimit: 3
gitlabUrl: http://89.169.128.88
runnerRegistrationToken: "glrt-gtzvzdkfbyu5zDb2q3we"
erminationGracePeriodSeconds: 3600
concurrent: 2
checkInterval: 30
logLevel: info
ogFormat: json
sessionServer:
  enabled: false
# rbac:
#   create: true
#   rules:
#     - resources: ["pods", "secrets", "configmaps"]
#       verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
#     - apiGroups: [""]
#       resources: ["pods/exec", "pods/attach"]
#       verbs: ["create", "patch", "delete"]
rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["pods", "configmaps", "jobs", "secrets", "cronjobs", "services", "deployments", "daemonsets", "statefulsets", "pods/attach", "pods/exec"]
      verbs: ["get", "list", "watch", "create", "update","delete"]
    - apiGroups: [""]
      resources: ["pods/log"]
      verbs: ["get"]
  clusterWideAccess: true 
  podSecurityPolicy:
    enabled: false
    resourceNames:
      - gitlab-runner
metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false
service:
  enabled: false
runners:
  privileged: true
  config: |
    [[runners]]
      output_limit = 10000
      [runners.kubernetes]
        namespace = "kube-system"
        image = "ubuntu:22.04"
        service_account = "admin-user"  
  executor: kubernetes
  secret: runner-secret
securityContext:
  runAsUser: 100
  fsGroup: 65533

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m