---
- name: Add helm apt Key 
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    keyring: /usr/share/keyrings/helm.gpg
    state: present

- name: Add k8s repo on 
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm-stable-debian
    update_cache: yes
    mode: 0644

- name: Install k8s packages
  ansible.builtin.apt:
    name:
      - helm
    state: present
    update_cache: yes
    force_apt_get: yes