---
all:
  hosts:
    k8s-node-01:
      ansible_host: 89.169.150.21
    k8s-node-02:
      ansible_host: 89.169.148.153
    k8s-node-03:
      ansible_host: 89.169.139.220
  vars:
    ansible_user: aspire