---
all:
  hosts:
    k8s-node-01:
      ansible_host: 51.250.11.190
    k8s-node-02:
      ansible_host: 51.250.80.23
    k8s-node-03:
      ansible_host: 51.250.77.247
  vars:
    ansible_user: aspire